import json

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# The Self-Pruning Neural Network\n",
    "\n",
    "This notebook implements a neural network that learns to prune itself during training by associating each weight with a learnable gate parameter. The sparsity loss has been normalized (using mean instead of sum) to ensure gradients flow effectively and encourage sparsity."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.nn.functional as F\n",
    "import torch.optim as optim\n",
    "from torchvision import datasets, transforms\n",
    "from torch.utils.data import DataLoader\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "import math\n",
    "import copy\n",
    "\n",
    "# Set device\n",
    "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "print(f'Using device: {device}')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. The Prunable Linear Layer\n",
    "We create a custom linear layer where `pruned_weights = weight * sigmoid(gate_scores)`."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "class PrunableLinear(nn.Module):\n",
    "    def __init__(self, in_features, out_features):\n",
    "        super(PrunableLinear, self).__init__()\n",
    "        self.in_features = in_features\n",
    "        self.out_features = out_features\n",
    "        \n",
    "        # Standard weight and bias\n",
    "        self.weight = nn.Parameter(torch.empty((out_features, in_features)))\n",
    "        self.bias = nn.Parameter(torch.empty(out_features))\n",
    "        \n",
    "        # Learnable gate scores, same shape as weight\n",
    "        self.gate_scores = nn.Parameter(torch.empty((out_features, in_features)))\n",
    "        \n",
    "        self.reset_parameters()\n",
    "\n",
    "    def reset_parameters(self):\n",
    "        # Initialize weights (Kaiming uniform for ReLU)\n",
    "        nn.init.kaiming_uniform_(self.weight, a=math.sqrt(5))\n",
    "        \n",
    "        # Initialize bias\n",
    "        fan_in, _ = nn.init._calculate_fan_in_and_fan_out(self.weight)\n",
    "        bound = 1 / math.sqrt(fan_in) if fan_in > 0 else 0\n",
    "        nn.init.uniform_(self.bias, -bound, bound)\n",
    "        \n",
    "        # Initialize gate scores to positive values (e.g. 1.0) so initial gates are ~0.73.\n",
    "        # This ensures gradients can flow initially and prevents premature pruning.\n",
    "        nn.init.normal_(self.gate_scores, mean=1.0, std=0.1)\n",
    "\n",
    "    def forward(self, x):\n",
    "        gates = torch.sigmoid(self.gate_scores)\n",
    "        pruned_weights = self.weight * gates\n",
    "        return F.linear(x, pruned_weights, self.bias)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Model Architecture\n",
    "A standard CNN feature extractor followed by `PrunableLinear` layers for classification."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "class SelfPruningNet(nn.Module):\n",
    "    def __init__(self):\n",
    "        super(SelfPruningNet, self).__init__()\n",
    "        # CNN Feature Extractor (Standard Conv layers)\n",
    "        self.features = nn.Sequential(\n",
    "            nn.Conv2d(3, 64, kernel_size=3, padding=1),\n",
    "            nn.BatchNorm2d(64),\n",
    "            nn.ReLU(inplace=True),\n",
    "            nn.MaxPool2d(2, 2),\n",
    "            \n",
    "            nn.Conv2d(64, 128, kernel_size=3, padding=1),\n",
    "            nn.BatchNorm2d(128),\n",
    "            nn.ReLU(inplace=True),\n",
    "            nn.MaxPool2d(2, 2),\n",
    "            \n",
    "            nn.Conv2d(128, 256, kernel_size=3, padding=1),\n",
    "            nn.BatchNorm2d(256),\n",
    "            nn.ReLU(inplace=True),\n",
    "            nn.MaxPool2d(2, 2),\n",
    "        )\n",
    "        \n",
    "        # Classifier with Prunable Layers\n",
    "        self.classifier = nn.Sequential(\n",
    "            nn.Flatten(),\n",
    "            PrunableLinear(256 * 4 * 4, 512),\n",
    "            nn.ReLU(inplace=True),\n",
    "            nn.Dropout(0.3),\n",
    "            \n",
    "            PrunableLinear(512, 256),\n",
    "            nn.ReLU(inplace=True),\n",
    "            nn.Dropout(0.3),\n",
    "            \n",
    "            PrunableLinear(256, 10)\n",
    "        )\n",
    "        \n",
    "    def forward(self, x):\n",
    "        x = self.features(x)\n",
    "        x = self.classifier(x)\n",
    "        return x\n",
    "    \n",
    "    def prunable_layers(self):\n",
    "        layers = []\n",
    "        for module in self.modules():\n",
    "            if isinstance(module, PrunableLinear):\n",
    "                layers.append(module)\n",
    "        return layers"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Sparsity Loss and Evaluation Metrics\n",
    "We use the L1 norm of the gates, **normalized by the total number of gates**, to keep the scale consistent regardless of network size. This fixes the issue where the sparsity gradient was overshadowed by the classification gradient."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def calculate_sparsity_loss(model):\n",
    "    \"\"\"\n",
    "    Returns the mean of all gate values. Using mean instead of sum\n",
    "    prevents the loss scale from dominating based on layer sizes.\n",
    "    \"\"\"\n",
    "    all_gates = []\n",
    "    for layer in model.prunable_layers():\n",
    "        all_gates.append(torch.sigmoid(layer.gate_scores).view(-1))\n",
    "    \n",
    "    if not all_gates:\n",
    "        return torch.tensor(0.0, device=device)\n",
    "        \n",
    "    return torch.cat(all_gates).mean()\n",
    "\n",
    "def calculate_sparsity_level(model, threshold=1e-2):\n",
    "    \"\"\"\n",
    "    Returns the percentage of gates that are below the given threshold.\n",
    "    \"\"\"\n",
    "    pruned = 0\n",
    "    total = 0\n",
    "    with torch.no_grad():\n",
    "        for layer in model.prunable_layers():\n",
    "            gates = torch.sigmoid(layer.gate_scores)\n",
    "            pruned += (gates < threshold).sum().item()\n",
    "            total += gates.numel()\n",
    "            \n",
    "    return (pruned / total) * 100.0\n",
    "\n",
    "def get_all_gates(model):\n",
    "    \"\"\"Returns a 1D numpy array of all gate values across the network.\"\"\"\n",
    "    all_gates = []\n",
    "    with torch.no_grad():\n",
    "        for layer in model.prunable_layers():\n",
    "            gates = torch.sigmoid(layer.gate_scores).cpu().numpy().flatten()\n",
    "            all_gates.extend(gates)\n",
    "    return np.array(all_gates)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Training Loop"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def train_model(lambda_val, epochs=20):\n",
    "    print(f\"\\n{'='*50}\")\n",
    "    print(f\"Training with λ = {lambda_val}\")\n",
    "    print(f\"{'='*50}\")\n",
    "    \n",
    "    # Data prep\n",
    "    transform_train = transforms.Compose([\n",
    "        transforms.RandomCrop(32, padding=4),\n",
    "        transforms.RandomHorizontalFlip(),\n",
    "        transforms.ToTensor(),\n",
    "        transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010))\n",
    "    ])\n",
    "    \n",
    "    transform_test = transforms.Compose([\n",
    "        transforms.ToTensor(),\n",
    "        transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010))\n",
    "    ])\n",
    "    \n",
    "    train_set = datasets.CIFAR10(root='./data', train=True, download=True, transform=transform_train)\n",
    "    test_set = datasets.CIFAR10(root='./data', train=False, download=True, transform=transform_test)\n",
    "    \n",
    "    train_loader = DataLoader(train_set, batch_size=128, shuffle=True, num_workers=2)\n",
    "    test_loader = DataLoader(test_set, batch_size=128, shuffle=False, num_workers=2)\n",
    "    \n",
    "    model = SelfPruningNet().to(device)\n",
    "    optimizer = optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-4)\n",
    "    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)\n",
    "    criterion = nn.CrossEntropyLoss()\n",
    "    \n",
    "    history = {'train_loss': [], 'test_acc': [], 'sparsity': []}\n",
    "    \n",
    "    for epoch in range(epochs):\n",
    "        model.train()\n",
    "        running_loss = 0.0\n",
    "        \n",
    "        for inputs, labels in train_loader:\n",
    "            inputs, labels = inputs.to(device), labels.to(device)\n",
    "            \n",
    "            optimizer.zero_grad()\n",
    "            outputs = model(inputs)\n",
    "            \n",
    "            clf_loss = criterion(outputs, labels)\n",
    "            sparsity_loss = calculate_sparsity_loss(model)\n",
    "            \n",
    "            loss = clf_loss + lambda_val * sparsity_loss\n",
    "            loss.backward()\n",
    "            optimizer.step()\n",
    "            \n",
    "            running_loss += loss.item()\n",
    "            \n",
    "        scheduler.step()\n",
    "        \n",
    "        # Evaluation\n",
    "        model.eval()\n",
    "        correct = 0\n",
    "        total = 0\n",
    "        with torch.no_grad():\n",
    "            for inputs, labels in test_loader:\n",
    "                inputs, labels = inputs.to(device), labels.to(device)\n",
    "                outputs = model(inputs)\n",
    "                _, predicted = outputs.max(1)\n",
    "                total += labels.size(0)\n",
    "                correct += predicted.eq(labels).sum().item()\n",
    "                \n",
    "        test_acc = 100. * correct / total\n",
    "        sparsity = calculate_sparsity_level(model)\n",
    "        \n",
    "        history['train_loss'].append(running_loss / len(train_loader))\n",
    "        history['test_acc'].append(test_acc)\n",
    "        history['sparsity'].append(sparsity)\n",
    "        \n",
    "        print(f\"Epoch {epoch+1:02d}/{epochs} | Loss: {running_loss/len(train_loader):.4f} | Test Acc: {test_acc:.2f}% | Sparsity: {sparsity:.2f}%\")\n",
    "        \n",
    "    return model, history"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 5. Experiment Execution\n",
    "We test different values of lambda to observe the sparsity-accuracy trade-off. With our normalized loss, values in the range `[0.0, 0.1, 1.0, 2.0]` are appropriate."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Set epochs (20-30 is recommended for CIFAR-10 to see full convergence, can reduce for quick tests)\n",
    "EPOCHS = 20\n",
    "lambdas = [0.0, 0.5, 2.0]\n",
    "results = {}\n",
    "models = {}\n",
    "\n",
    "for l_val in lambdas:\n",
    "    model, history = train_model(l_val, epochs=EPOCHS)\n",
    "    results[l_val] = history\n",
    "    models[l_val] = copy.deepcopy(model.state_dict()) # Save weights"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 6. Visualizations and Results"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 1. Summary Table\n",
    "print(\"\\n=== Final Results Summary ===\")\n",
    "print(f\"{'Lambda':<10} | {'Test Acc (%)':<15} | {'Sparsity Level (%)':<20}\")\n",
    "print(\"-\" * 50)\n",
    "for l_val in lambdas:\n",
    "    final_acc = results[l_val]['test_acc'][-1]\n",
    "    final_spars = results[l_val]['sparsity'][-1]\n",
    "    print(f\"{l_val:<10.1f} | {final_acc:<15.2f} | {final_spars:<20.2f}\")\n",
    "\n",
    "# 2. Plot Sparsity vs Accuracy Trade-off\n",
    "plt.figure(figsize=(8, 5))\n",
    "final_accs = [results[l]['test_acc'][-1] for l in lambdas]\n",
    "final_sparsities = [results[l]['sparsity'][-1] for l in lambdas]\n",
    "\n",
    "plt.plot(final_sparsities, final_accs, 'mo-', markersize=8, linewidth=2)\n",
    "for i, l in enumerate(lambdas):\n",
    "    plt.annotate(f\"λ={l}\", (final_sparsities[i], final_accs[i]), textcoords=\"offset points\", xytext=(0,10), ha='center')\n",
    "plt.title('Sparsity vs Test Accuracy Trade-off')\n",
    "plt.xlabel('Sparsity Level (%)')\n",
    "plt.ylabel('Test Accuracy (%)')\n",
    "plt.grid(True, linestyle='--', alpha=0.7)\n",
    "plt.tight_layout()\n",
    "plt.savefig('sparsity_vs_accuracy.png')\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 3. Gate Distribution Plot for Best Pruned Model\n",
    "# We consider the model with the highest sparsity that maintains decent accuracy.\n",
    "best_lambda = lambdas[-1] # Usually the highest lambda gives the most sparsity\n",
    "\n",
    "best_model = SelfPruningNet().to(device)\n",
    "best_model.load_state_dict(models[best_lambda])\n",
    "all_gates = get_all_gates(best_model)\n",
    "\n",
    "plt.figure(figsize=(10, 6))\n",
    "plt.hist(all_gates, bins=50, color='teal', edgecolor='black', alpha=0.7)\n",
    "plt.title(f'Distribution of Final Gate Values (λ = {best_lambda})')\n",
    "plt.xlabel('Gate Value (after Sigmoid)')\n",
    "plt.ylabel('Frequency')\n",
    "plt.yscale('log') # Log scale is better to see both the huge spike at 0 and the rest\n",
    "plt.grid(True, alpha=0.3)\n",
    "plt.tight_layout()\n",
    "plt.savefig('gate_distribution.png')\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 4. Training Curves\n",
    "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 5))\n",
    "\n",
    "for l_val in lambdas:\n",
    "    ax1.plot(results[l_val]['test_acc'], label=f'λ={l_val}')\n",
    "    ax2.plot(results[l_val]['sparsity'], label=f'λ={l_val}')\n",
    "\n",
    "ax1.set_title('Test Accuracy over Epochs')\n",
    "ax1.set_xlabel('Epoch')\n",
    "ax1.set_ylabel('Accuracy (%)')\n",
    "ax1.legend()\n",
    "ax1.grid(True, alpha=0.3)\n",
    "\n",
    "ax2.set_title('Sparsity Level over Epochs')\n",
    "ax2.set_xlabel('Epoch')\n",
    "ax2.set_ylabel('Sparsity (%)')\n",
    "ax2.legend()\n",
    "ax2.grid(True, alpha=0.3)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig('training_curves.png')\n",
    "plt.show()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open("d:\\Projects and Coding\\Version Control Systems\\Trendance\\self_pruning_nn.ipynb", "w") as f:
    json.dump(notebook, f, indent=1)
